version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mi_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data   # datos persistentes
      - ./init-db:/docker-entrypoint-initdb.d     # scripts iniciales

  streamlit-app:
    build: ./app-streamlit
    ports:
      - "8501:8501"
    environment:
      DB_HOST: postgres   # nombre del servicio, no localhost
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres

  nodejs-app:
    build: ./app-nodejs
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    depends_on:
      - postgres

volumes:
  postgres_data: